---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-live
  labels:
    app: go-live
spec:
  replicas: 6
  selector:
    matchLabels:
      app: go-live
  template:
    metadata:
      labels:
        app: go-live
    spec:
      containers:
      - name: go-live
        image: localhost/go-live:0.0.3
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: go-live
  name: go-live
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: go-live
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: go-live
spec:
  rules:
  - host: localhost
    http:
      paths:
      - backend:
          serviceName: go-live
          servicePort: 8080
        path: /