---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cavalo
  labels:
    app: cavalo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cavalo
  template:
    metadata:
      labels:
        app: cavalo
    spec:
      containers:
      - name: cavalo
        image: hashicorp/http-echo
        imagePullPolicy: IfNotPresent
        args:
          - "-text=cavalo"
        ports:
          - containerPort: 5678
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cavalo
  name: cavalo
spec:
  ports:
  - port: 5678
    protocol: TCP
    targetPort: 5678
  selector:
    app: cavalo
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cavalo
spec:
  rules:
  - host: localhost
    http:
      paths:
      - backend:
          serviceName: cavalo
          servicePort: 5678
        path: /cavalo