---
apiVersion: v1
kind: Namespace
metadata:
  name: app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: maracuja
  namespace: app
  labels:
    app: maracuja
spec:
  replicas: 3
  selector:
    matchLabels:
      app: maracuja
  template:
    metadata:
      labels:
        app: maracuja
    spec:
      containers:
      - name: maracuja
        image: hashicorp/http-echo
        imagePullPolicy: IfNotPresent
        args:
          - "-text=maracuja"      
        ports:
          - containerPort: 5678
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: maracuja
  name: maracuja
  namespace: app
spec:
  ports:
  - port: 5678
    protocol: TCP
    targetPort: 5678
  selector:
    app: maracuja
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: maracuja
  namespace: app
spec:
  rules:
  - host: localhost
    http:
      paths:
      - backend:
          serviceName: maracuja
          servicePort: 5678
        path: /maracuja