apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api
  namespace: argocd  
spec:
  destination:
    name: ''
    namespace: app
    server: 'https://kubernetes.default.svc'
  source:
    path: app/api/deploy
    repoURL: 'https://github.com/uknbr/go-live.git'
    targetRevision: main
  syncPolicy:
    automated: {}
  project: playground